version: "3.9"
services:
  db:
    image: mysql
    command: --max_connections=10000
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "6033:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_tfg
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  web:
#    platform: linux/x86_64
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: rails
#    restart: always
    environment:
      - GMAIL_PASS=${GMAIL_PASS}
    volumes:
      - .:/tfg
    ports:
      - "3000:3000"
    depends_on:
      - db