source 'https://rubygems.org'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~>7.0.1'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'